package com.burgerburst.entity;

public enum PaymentAuditType {
    PROVIDER_ORDER_CREATED,
    VERIFICATION_SUCCESS,
    VERIFICATION_FAILED,
    WEBHOOK_PAYMENT_CAPTURED,
    WEBHOOK_PAYMENT_FAILED,
    WEBHOOK_REFUND_PROCESSED,
    REFUND_REQUESTED,
    REFUND_FAILED
}

